extends RefCounted

# Generated by scripts/tools/build_combat_audio.py. Tune profiles there.
const PROFILES: Dictionary = {
	"wood_arrow": {"streams": [preload("res://assets/audio/sfx/combat/wood_arrow_01.wav")], "gain_db": -7, "cooldown_ms": 65, "max_voices": 3, "priority": 2, "pitch_spread": 0.035},
	"plasma_hit": {"streams": [preload("res://assets/audio/sfx/combat/plasma_hit_01.wav")], "gain_db": -10, "cooldown_ms": 160, "max_voices": 2, "priority": 2, "pitch_spread": 0.025},
	"lightning": {"streams": [preload("res://assets/audio/sfx/combat/lightning_01.wav")], "gain_db": -10, "cooldown_ms": 110, "max_voices": 2, "priority": 1, "pitch_spread": 0.035},
	"spark_charge": {"streams": [preload("res://assets/audio/sfx/combat/spark_charge_01.wav")], "gain_db": -17, "cooldown_ms": 350, "max_voices": 1, "priority": 0, "pitch_spread": 0},
	"electric_spark": {"streams": [preload("res://assets/audio/sfx/combat/electric_spark_01.wav")], "gain_db": -9, "cooldown_ms": 200, "max_voices": 2, "priority": 2, "pitch_spread": 0.02},
	"fire": {"streams": [preload("res://assets/audio/sfx/combat/fire_01.wav")], "gain_db": -12, "cooldown_ms": 260, "max_voices": 2, "priority": 1, "pitch_spread": 0.035},
	"explosion": {"streams": [preload("res://assets/audio/sfx/combat/explosion_01.wav")], "gain_db": -10, "cooldown_ms": 230, "max_voices": 2, "priority": 2, "pitch_spread": 0.035},
	"water": {"streams": [preload("res://assets/audio/sfx/combat/water_01.wav")], "gain_db": -11, "cooldown_ms": 180, "max_voices": 2, "priority": 1, "pitch_spread": 0.035},
	"ice": {"streams": [preload("res://assets/audio/sfx/combat/ice_01.wav")], "gain_db": -12, "cooldown_ms": 240, "max_voices": 2, "priority": 1, "pitch_spread": 0.025},
	"wind": {"streams": [preload("res://assets/audio/sfx/combat/wind_01.wav")], "gain_db": -12, "cooldown_ms": 180, "max_voices": 2, "priority": 1, "pitch_spread": 0.035},
	"light_sword": {"streams": [preload("res://assets/audio/sfx/combat/light_sword_01.wav")], "gain_db": -10, "cooldown_ms": 260, "max_voices": 2, "priority": 2, "pitch_spread": 0.015},
	"black_hole": {"streams": [preload("res://assets/audio/sfx/combat/black_hole_01.wav")], "gain_db": -13, "cooldown_ms": 550, "max_voices": 1, "priority": 1, "pitch_spread": 0.02},
	"reaction_steam": {"streams": [preload("res://assets/audio/sfx/combat/reaction_steam_01.wav")], "gain_db": -13, "cooldown_ms": 330, "max_voices": 1, "priority": 2, "pitch_spread": 0.025},
	"reaction_freeze": {"streams": [preload("res://assets/audio/sfx/combat/reaction_freeze_01.wav")], "gain_db": -11, "cooldown_ms": 300, "max_voices": 1, "priority": 2, "pitch_spread": 0.02},
	"reaction_thaw": {"streams": [preload("res://assets/audio/sfx/combat/reaction_thaw_01.wav")], "gain_db": -17, "cooldown_ms": 400, "max_voices": 1, "priority": 0, "pitch_spread": 0.025},
	"reaction_holy": {"streams": [preload("res://assets/audio/sfx/combat/reaction_holy_01.wav")], "gain_db": -13, "cooldown_ms": 450, "max_voices": 1, "priority": 2, "pitch_spread": 0.015},
	"reaction_dark_flame": {"streams": [preload("res://assets/audio/sfx/combat/reaction_dark_flame_01.wav")], "gain_db": -14, "cooldown_ms": 500, "max_voices": 1, "priority": 2, "pitch_spread": 0.02},
	"reaction_cancel": {"streams": [preload("res://assets/audio/sfx/combat/reaction_cancel_01.wav")], "gain_db": -12, "cooldown_ms": 350, "max_voices": 1, "priority": 2, "pitch_spread": 0.02},
	"reaction_conduct": {"streams": [preload("res://assets/audio/sfx/combat/reaction_conduct_01.wav")], "gain_db": -14, "cooldown_ms": 240, "max_voices": 1, "priority": 2, "pitch_spread": 0.035},
	"reaction_thunder_fire": {"streams": [preload("res://assets/audio/sfx/combat/reaction_thunder_fire_01.wav")], "gain_db": -10, "cooldown_ms": 300, "max_voices": 2, "priority": 2, "pitch_spread": 0.025},
	"reaction_wet_spread": {"streams": [preload("res://assets/audio/sfx/combat/reaction_wet_spread_01.wav")], "gain_db": -16, "cooldown_ms": 350, "max_voices": 1, "priority": 0, "pitch_spread": 0.03},
	"reaction_ice_expand": {"streams": [preload("res://assets/audio/sfx/combat/reaction_ice_expand_01.wav")], "gain_db": -15, "cooldown_ms": 350, "max_voices": 1, "priority": 1, "pitch_spread": 0.02},
	"reaction_reflection": {"streams": [preload("res://assets/audio/sfx/combat/reaction_reflection_01.wav")], "gain_db": -12, "cooldown_ms": 450, "max_voices": 1, "priority": 2, "pitch_spread": 0.015},
}
