extends RefCounted
## Offline GPU captures of the original pixel geometry. No live viewport baking.
const definitions: Dictionary = {"ice_d0": {"size": [128, 80], "origin": [-64, -40], "count": 37, "fps": 60}, "hole_d0": {"size": [208, 208], "origin": [-104, -104], "count": 52, "fps": 60}, "sword_wait_d0": {"size": [80, 272], "origin": [-40, -246], "count": 1, "fps": 60}, "sword_fall_d0": {"size": [80, 272], "origin": [-40, -246], "count": 15, "fps": 60}, "sword_land_d0": {"size": [80, 144], "origin": [-40, -118], "count": 46, "fps": 60}, "ice_d1": {"size": [128, 80], "origin": [-64, -40], "count": 37, "fps": 60}, "hole_d1": {"size": [208, 208], "origin": [-104, -104], "count": 52, "fps": 60}, "sword_wait_d1": {"size": [80, 272], "origin": [-40, -246], "count": 1, "fps": 60}, "sword_fall_d1": {"size": [80, 272], "origin": [-40, -246], "count": 15, "fps": 60}, "sword_land_d1": {"size": [80, 144], "origin": [-40, -118], "count": 46, "fps": 60}, "ice_d2": {"size": [128, 80], "origin": [-64, -40], "count": 37, "fps": 60}, "hole_d2": {"size": [208, 208], "origin": [-104, -104], "count": 52, "fps": 60}, "sword_wait_d2": {"size": [80, 272], "origin": [-40, -246], "count": 1, "fps": 60}, "sword_fall_d2": {"size": [80, 272], "origin": [-40, -246], "count": 15, "fps": 60}, "sword_land_d2": {"size": [80, 144], "origin": [-40, -118], "count": 46, "fps": 60}, "hole_shadow": {"size": [48, 20], "origin": [-24, -10], "count": 52, "fps": 60}, "sword_mark": {"size": [32, 32], "origin": [-16, -16], "count": 1, "fps": 60}, "sword_cracks": {"size": [72, 16], "origin": [-36, -8], "count": 1, "fps": 60}, "steam_d0": {"size": [96, 96], "origin": [-48, -80], "count": 67, "fps": 60}, "frost_front_d0": {"size": [160, 96], "origin": [-80, -48], "count": 44, "fps": 60}, "steam_d1": {"size": [96, 96], "origin": [-48, -80], "count": 67, "fps": 60}, "frost_front_d1": {"size": [160, 96], "origin": [-80, -48], "count": 44, "fps": 60}, "conduct": {"size": [48, 32], "origin": [-24, -26], "count": 14, "fps": 12}, "grenade": {"size": [144, 144], "origin": [-72, -72], "count": 31, "fps": 60}, "tome": {"size": [96, 96], "origin": [-48, -52], "count": 37, "fps": 60}, "coin_hit": {"size": [80, 80], "origin": [-40, -32], "count": 25, "fps": 60}, "ice_shell": {"size": [72, 72], "origin": [-36, -42], "count": 11, "fps": 60}, "slowed": {"size": [64, 40], "origin": [-32, -20], "count": 1, "fps": 60}, "shard": {"size": [64, 32], "origin": [-24, -16], "count": 1, "fps": 60}, "star": {"size": [24, 28], "origin": [-12, -14], "count": 1, "fps": 60}, "reflection_beam": {"size": [236, 20], "origin": [-8, -10], "count": 1, "fps": 60}, "reflection_sides": {"size": [220, 20], "origin": [16, -10], "count": 1, "fps": 60}}
const textures: Dictionary = {"ice_d0":preload("res://assets/effects/pixel_baked/ice_d0.png"),"hole_d0":preload("res://assets/effects/pixel_baked/hole_d0.png"),"sword_wait_d0":preload("res://assets/effects/pixel_baked/sword_wait_d0.png"),"sword_fall_d0":preload("res://assets/effects/pixel_baked/sword_fall_d0.png"),"sword_land_d0":preload("res://assets/effects/pixel_baked/sword_land_d0.png"),"ice_d1":preload("res://assets/effects/pixel_baked/ice_d1.png"),"hole_d1":preload("res://assets/effects/pixel_baked/hole_d1.png"),"sword_wait_d1":preload("res://assets/effects/pixel_baked/sword_wait_d1.png"),"sword_fall_d1":preload("res://assets/effects/pixel_baked/sword_fall_d1.png"),"sword_land_d1":preload("res://assets/effects/pixel_baked/sword_land_d1.png"),"ice_d2":preload("res://assets/effects/pixel_baked/ice_d2.png"),"hole_d2":preload("res://assets/effects/pixel_baked/hole_d2.png"),"sword_wait_d2":preload("res://assets/effects/pixel_baked/sword_wait_d2.png"),"sword_fall_d2":preload("res://assets/effects/pixel_baked/sword_fall_d2.png"),"sword_land_d2":preload("res://assets/effects/pixel_baked/sword_land_d2.png"),"hole_shadow":preload("res://assets/effects/pixel_baked/hole_shadow.png"),"sword_mark":preload("res://assets/effects/pixel_baked/sword_mark.png"),"sword_cracks":preload("res://assets/effects/pixel_baked/sword_cracks.png"),"steam_d0":preload("res://assets/effects/pixel_baked/steam_d0.png"),"frost_front_d0":preload("res://assets/effects/pixel_baked/frost_front_d0.png"),"steam_d1":preload("res://assets/effects/pixel_baked/steam_d1.png"),"frost_front_d1":preload("res://assets/effects/pixel_baked/frost_front_d1.png"),"conduct":preload("res://assets/effects/pixel_baked/conduct.png"),"grenade":preload("res://assets/effects/pixel_baked/grenade.png"),"tome":preload("res://assets/effects/pixel_baked/tome.png"),"coin_hit":preload("res://assets/effects/pixel_baked/coin_hit.png"),"ice_shell":preload("res://assets/effects/pixel_baked/ice_shell.png"),"slowed":preload("res://assets/effects/pixel_baked/slowed.png"),"shard":preload("res://assets/effects/pixel_baked/shard.png"),"star":preload("res://assets/effects/pixel_baked/star.png"),"reflection_beam":preload("res://assets/effects/pixel_baked/reflection_beam.png"),"reflection_sides":preload("res://assets/effects/pixel_baked/reflection_sides.png")}
static func draw(canvas: CanvasItem, key: String, frame: int = 0, size: Vector2 = Vector2.ONE, tint: Color = Color.WHITE) -> void:
	if canvas.texture_filter != CanvasItem.TEXTURE_FILTER_NEAREST:
		canvas.texture_filter = CanvasItem.TEXTURE_FILTER_NEAREST
	if not definitions.has(key): return
	var d: Dictionary = definitions[key]
	var index := clampi(frame, 0, int(d.count) - 1)
	var extent := Vector2(d.size[0], d.size[1])
	var origin := Vector2(d.origin[0], d.origin[1])
	canvas.draw_texture_rect_region(textures[key], Rect2(origin * size, extent * size), Rect2(Vector2(index % 8, index / 8) * extent, extent), tint)
